# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - '5430:5432'
  # volumes:
  # - ./db/data:/tmp/data
  # - ./db/init:/docker-entrypoint-initdb.d/


  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080